services:
  bot:
    build: .
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      DB_FILE_NAME: "data/bot.db"
    restart: unless-stopped
    volumes:
      - scratch-data:/app/data

volumes:
  scratch-data:
